import { CurrentSubscription, PackageHistoryItem, PackagePlan } from "./types";

export const DEFAULT_PACKAGES: PackagePlan[] = [
  {
    id: "pkg-family",
    name: "الباقة العائلية",
    description: "الباقة المثالية للعائلات التي تضم أكثر من طفل",
    audience: "family",
    icon: "/iamges/family-icon.svg",
    ageCategories: ["3-6", "7-10", "11-13"],
    price: 149,
    currency: "ر.س",
    durationLabel: "شهرياً",
    annualNote: "قيمة سنوية 1490 شاملة",
    features: [
      "كل مميزات الباقة المتقدمة",
      "تفعيل حتى 5 حسابات للأطفال",
      "تقارير نمو دورية وشهرية للوالدين",
      "دعم أولوية 24/7 وإرشادات تربوية",
    ],
    ctaType: "checkout",
    ctaText: "اشترك الآن",
    isFeatured: true,
  },
  {
    id: "pkg-school",
    name: "باقة المدارس",
    description: "حل متكامل للمدارس والمعلمين",
    audience: "school",
    icon: "/iamges/school-icon.svg",
    ageCategories: ["3-6", "7-10", "11-13"],
    price: null,
    features: [
      "إنشاء فصول دراسية وإدارة الطلاب",
      "متابعة أداء الطلاب وإصدار التقارير",
      "مكتبة قصص وشاشات مخصصة",
      "اختبارات تقييمية",
    ],
    ctaType: "whatsapp",
    ctaText: "اشترك عبر الواتساب",
    ctaLink: "https://wa.me/966500000000",
  },
];

export const DEFAULT_CURRENT_SUBSCRIPTION: CurrentSubscription = {
  id: "sub-2026-01",
  planName: "الباقة المتقدمة",
  subtitle: "اشتراك طفلك الحالي النشط",
  ageCategory: "6-8 سنوات",
  startDate: "15 فبراير 2026",
  endDate: "15 فبراير 2027",
  autoRenewDate: "30 سبتمبر 2026",
  paymentMethod: "دفع سنوي (1,490 ر.س)",
  monthlyPriceText: "149 ر.س / شهرياً",
  annualPriceText: "1,490 ر.س",
  status: "active",
  statusLabel: "نشط",
  description:
    "سيتم التجديد تلقائياً في 30 سبتمبر 2026، بإمكانك تجديد اشتراكك أو تغييره باقة متقدمة في أي وقت.",
};

export const DEFAULT_PACKAGE_HISTORY: PackageHistoryItem[] = [
  {
    id: "hist-1",
    invoiceNumber: "INV-91214",
    packageName: "الباقة المتقدمة",
    packageType: "سنوي",
    ageCategory: "6-8 سنوات",
    price: "1490 ر.س",
    currency: "ر.س",
    startDate: "15 فبراير 2026",
    endDate: "15 فبراير 2027",
    status: "active",
    statusLabel: "نشط",
    paymentMethod: "بطاقة ائتمان",
  },
  {
    id: "hist-2",
    invoiceNumber: "INV-88132",
    packageName: "الباقة الشهرية",
    packageType: "شهري",
    ageCategory: "3-5 سنوات",
    price: "149 ر.س",
    currency: "ر.س",
    startDate: "10 يناير 2025",
    endDate: "10 فبراير 2025",
    status: "expired",
    statusLabel: "منتهية",
    paymentMethod: "بطاقة ائتمان",
  },
  {
    id: "hist-3",
    invoiceNumber: "INV-74139",
    packageName: "باقة تجربة الاستكشاف",
    packageType: "مجاني",
    ageCategory: "جميع الأعمار",
    price: "مجاني",
    currency: "",
    startDate: "01 يناير 2024",
    endDate: "01 يناير 2025",
    status: "free",
    statusLabel: "مجانية",
    paymentMethod: "مجاني",
  },
  {
    id: "hist-4",
    invoiceNumber: "INV-43211",
    packageName: "الباقة الذهبية",
    packageType: "سنوي",
    ageCategory: "7-9 سنوات",
    price: "290 ر.س",
    currency: "ر.س",
    startDate: "20 نوفمبر 2024",
    endDate: "20 ديسمبر 2024",
    status: "cancelled",
    statusLabel: "ملغاة",
    paymentMethod: "بطاقة ائتمان",
  },
];
