export const AUTH_TEXTS = {
  login: {
    logoAlt: "شعار مدارك القراءة",
    heading: "مرحبا بك من جديد!",
    phoneLabel: "رقم الهاتف",
    phonePlaceholder: "ادخل رقم هاتفك",
    countryCode: "+992",
    passwordLabel: "كلمة المرور",
    passwordPlaceholder: "••••••••",
    forgotPassword: "هل نسيت كلمة المرور؟",
    submitButton: "تسجيل الدخول",
    submittingButton: "جاري تسجيل الدخول...",
    noAccount: "ليس لديك حساب؟ ",
    createAccount: "إنشاء حساب",
    hidePasswordLabel: "إخفاء كلمة المرور",
    showPasswordLabel: "إظهار كلمة المرور",
  },
  register: {
    logoAlt: "شعار مدارك القراءة",
    heading: "إنشاء حساب",
    usernameLabel: "اسم المستخدم",
    usernamePlaceholder: "ادخل اسمك بالكامل",
    phoneLabel: "رقم الهاتف",
    phonePlaceholder: "ادخل رقم هاتفك",
    countryCode: "+992",
    passwordLabel: "كلمة المرور",
    passwordPlaceholder: "••••••••",
    confirmPasswordLabel: "تأكيد كلمة المرور",
    confirmPasswordPlaceholder: "••••••••",
    submitButton: "إرسال رمز التحقق",
    submittingButton: "جاري الإرسال...",
    hasAccount: "لديك حساب بالفعل؟ ",
    loginLink: "تسجيل الدخول",
    hidePasswordLabel: "إخفاء كلمة المرور",
    showPasswordLabel: "إظهار كلمة المرور",
  },
  otp: {
    lockAlt: "أيقونة قفل التحقق",
    heading: "تحقق من رقم الجوال",
    description: "أرسلنا رمز تحقق مكوّن من 6 أرقام إلى رقم الجوال:",
    defaultPhone: "+966 555 *** 458",
    instruction: "يرجى إدخال الرمز للمتابعة.",
    resendText: "إعادة إرسال الرمز",
    resendTimerPrefix: "يمكنك إعادة إرسال الرمز خلال",
    confirmButton: "تأكيد",
    submittingButton: "جاري التحقق...",
  },
  sidePanel: {
    alt: "لوحة المصادقة",
  },
  resetFirstPassword: {
    heading: "تعيين كلمة المرور الجديدة",
    description: "تمت إعادة تعيين كلمة المرور الخاصة بك من قِبل المسؤول. يرجى تعيين كلمة مرور جديدة لحسابك للمتابعة.",
    passwordLabel: "كلمة المرور الجديدة",
    passwordPlaceholder: "••••••••",
    confirmPasswordLabel: "تأكيد كلمة المرور الجديدة",
    confirmPasswordPlaceholder: "••••••••",
    submitButton: "حفظ ومتابعة",
    submittingButton: "جاري الحفظ...",
    logoutText: "تسجيل الخروج والعودة لاحقاً",
  },
  forgotPasswordFlow: {
    logoAlt: "شعار مدارك القراءة",
    phoneStepHeading: "استعادة كلمة المرور",
    phoneStepDescription: "أدخل رقم هاتفك المسجل وسنرسل لك رمز تحقق لإعادة تعيين كلمة المرور",
    phoneLabel: "رقم الهاتف",
    phonePlaceholder: "ادخل رقم هاتفك",
    submitPhoneButton: "إرسال رمز التحقق",
    submittingPhoneButton: "جاري الإرسال...",
    rememberPassword: "تذكرت كلمة المرور؟ ",
    loginLink: "تسجيل الدخول",
    backToLogin: "العودة لتسجيل الدخول",
    otpStepHeading: "تحقق من رقم الجوال",
    otpStepDescription: "أرسلنا رمز تحقق مكوّن من 6 أرقام إلى رقم الجوال:",
    newPasswordHeading: "تعيين كلمة المرور الجديدة",
    newPasswordDescription: "أدخل كلمة المرور الجديدة لحسابك وتأكيدها للمتابعة",
    passwordLabel: "كلمة المرور الجديدة",
    passwordPlaceholder: "••••••••",
    confirmPasswordLabel: "تأكيد كلمة المرور الجديدة",
    confirmPasswordPlaceholder: "••••••••",
    submitNewPasswordButton: "حفظ كلمة المرور وتأكيدها",
    submittingNewPasswordButton: "جاري حفظ كلمة المرور...",
    hidePasswordLabel: "إخفاء كلمة المرور",
    showPasswordLabel: "إظهار كلمة المرور",
  },

  validation: {
    usernameRequired: "اسم المستخدم مطلوب",
    phoneRequired: "رقم الهاتف مطلوب",
    passwordRequired: "كلمة المرور مطلوبة",
    passwordMinLength: "كلمة المرور يجب أن لا تقل عن 6 أحرف",
    passwordMatch: "كلمتا المرور غير متطابقتين",
    otpInvalid: "يرجى إدخال رمز التحقق المكون من 6 أرقام كاملة",
  },
};


export const AUTH_TYPOGRAPHY = {
  heading: "mad-h4 md:mad-h3 font-extrabold",
  label: "mad-label-2 font-semibold",
  input: "mad-body-3",
  countryCode: "mad-label-2 font-semibold",
  forgotPassword: "mad-body-4 sm:mad-body-3 font-semibold",
  error: "mad-caption-1",
  button: "mad-label-1 font-bold",
  footer: "mad-body-3",
  otpHeading: "mad-h4 md:mad-h3 font-extrabold",
  otpDescription: "mad-body-3 font-normal",
  otpPhone: "mad-body-3 font-medium",
  otpBox: "mad-h4 font-bold text-center",
  otpResend: "mad-body-3 font-medium",
  otpTimer: "mad-body-3 font-bold",
};

export const AUTH_COLORS = {
  heading: "text-mad-text-primary",
  label: "text-mad-text-primary",
  required: "text-mad-danger",
  inputBorder: "border-mad-white-200",
  inputFocusBorder: "focus-within:border-mad-main focus-within:ring-mad-main",
  countryCode: "text-mad-text-secondary",
  inputText: "text-mad-text-primary",
  inputPlaceholder: "placeholder-mad-white-400",
  eyeIcon: "text-mad-white-400 hover:text-mad-white-600",
  forgotPassword: "text-mad-purple-600 hover:text-mad-main",
  submitButton: "bg-mad-main hover:bg-mad-purple-800 text-white",
  footerText: "text-mad-text-secondary",
  footerLink: "text-mad-text-primary hover:text-mad-main",
  errorText: "text-mad-danger",
  otpBoxBorder: "border-mad-white-200 focus:border-mad-main focus:ring-1 focus:ring-mad-main",
  otpBoxActive: "border-mad-main ring-1 ring-mad-main",
  otpResendLink: "text-mad-text-secondary hover:text-mad-main underline cursor-pointer",
  otpTimerText: "text-mad-main",
};



